package requests

type HeaderDeliveryDocumentHeader struct {
	InvoiceDocument               *int     `json:"InvoiceDocument"`
	DeliveryDocument              *int     `json:"DeliveryDocument"`
	Buyer                         *int     `json:"Buyer`
	Seller                        *int     `json:"Seller"`
	ReferenceDocument             *int     `json:"ReferenceDocument"`
	ReferenceDocumentItem         *int     `json:"ReferenceDocumentItem"`
	OrderID                       *string  `json:"OrderID"`
	OrderItem                     *string  `json:"OrderItem"`
	ContractType                  *string  `json:"ContractType"`
	OrderValidityStartDate        *string  `json:"OrderValidityStartDate"`
	OrderValidityEndDate          *string  `json:"OrderValidityEndDate"`
	InvoiceScheduleStartDate      *string  `json:"InvoiceScheduleStartDate"`
	InvoiceScheduleEndDate        *string  `json:"InvoiceScheduleEndDate"`
	IssuingPlantTimeZone          *string  `json:"IssuingPlantTimeZone"`
	ReceivingPlantTimeZone        *string  `json:"ReceivingPlantTimeZone"`
	DocumentDate                  *string  `json:"DocumentDate"`
	PlannedGoodsIssueDate         *string  `json:"PlannedGoodsIssueDate"`
	PlannedGoodsIssueTime         *string  `json:"PlannedGoodsIssueTime"`
	PlannedGoodsReceiptDate       *string  `json:"PlannedGoodsReceiptDate"`
	PlannedGoodsReceiptTime       *string  `json:"PlannedGoodsReceiptTime"`
	BillingDocumentDate           *string  `json:"BillingDocumentDate"`
	CompleteDeliveryIsDefined     *bool    `json:"CompleteDeliveryIsDefined"`
	OverallDeliveryStatus         *string  `json:"OverallDeliveryStatus"`
	CreationDate                  *string  `json:"CreationDate`
	CreationTime                  *string  `json:"CreationTime"`
	IssuingBlockReason            *bool    `json:"IssuingBlockReason"`
	ReceivingBlockReason          *bool    `json:"ReceivingBlockReason"`
	GoodsIssueOrReceiptSlipNumber *string  `json:"GoodsIssueOrReceiptSlipNumber"`
	HeaderBillingStatus           *string  `json:"HeaderBillingStatus"`
	HeaderBillingConfStatus       *string  `json:"HeaderBillingConfStatus"`
	HeaderBillingBlockReason      *bool    `json:"HeaderBillingBlockReason"`
	HeaderGrossWeight             *float32 `json:"HeaderGrossWeight"`
	HeaderNetWeight               *float32 `json:"HeaderNetWeight"`
	HeaderWeightUnit              *string  `json:"HeaderWeightUnit"`
	Incoterms                     *string  `json:"Incoterms"`
	BillToCountry                 *string  `json:"BillToCountry"`
	BillFromCountry               *string  `json:"BillFromCountry"`
	IsExportImportDelivery        *bool    `json:"IsExportImportDelivery"`
	LastChangeDate                *string  `json:"LastChangeDate"`
	IssuingPlantBusinessPartner   *int     `json:"IssuingPlantBusinessPartner"`
	IssuingPlant                  *string  `json:"IssuingPlant"`
	ReceivingPlantBusinessPartner *int     `json:"ReceivingPlantBusinessPartner"`
	ReceivingPlant                *string  `json:"ReceivingPlant"`
	DeliverToParty                *int     `json:"DeliverToParty"`
	DeliverFromParty              *int     `json:"DeliverFromParty"`
	TransactionCurrency           *string  `json:"TransactionCurrency"`
	OverallDelivReltdBillgStatus  *string  `json:"OverallDelivReltdBillgStatus"`
	StockIsFullyConfirmed         *bool    `json:"StockIsFullyConfirmed"`
}
